apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:latest # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 4222
            - containerPort: 8222
            - containerPort: 6222  # Exposes container port